export interface CSSProperties {
  "align-content": string
  "align-items": string
  "align-self": string
  "alignment-baseline": string
  all: string
  animation: string
  "animation-delay": string
  "animation-direction": string
  "animation-duration": string
  "animation-fill-mode": string
  "animation-iteration-count": string
  "animation-name": string
  "animation-play-state": string
  "animation-timing-function": string
  "backface-visibility": "visible" | "hidden"
  background: string
  "background-attachment": "scroll" | "fixed" | "local"
  "background-blend-mode":
    | "normal"
    | "multiply"
    | "screen"
    | "overlay"
    | "darken"
    | "lighten"
    | "color-dodge"
    | "color-burn"
    | "hard-light"
    | "soft-light"
    | "difference"
    | "exclusion"
    | "hue"
    | "saturation"
    | "color"
    | "luminosity"
  "background-clip": "border-box" | "padding-box" | "content-box" | "text"
  "background-color": string
  "background-image": string
  "background-origin": "border-box" | "padding-box" | "content-box"
  "background-position": string
  "background-position-x": string
  "background-position-y": string
  "background-repeat": "repeat" | "repeat-x" | "repeat-y" | "no-repeat" | "space" | "round"
  "background-size": string
  "baseline-shift": string
  "block-size": string
  border: string
  "border-block-end": string
  "border-block-end-color": string
  "border-block-end-style": string
  "border-block-end-width": string
  "border-block-start": string
  "border-block-start-color": string
  "border-block-start-style": string
  "border-block-start-width": string
  "border-bottom": string
  "border-bottom-color": string
  "border-bottom-left-radius": string
  "border-bottom-right-radius": string
  "border-bottom-style": string
  "border-bottom-width": string
  "border-collapse": "collapse" | "separate"
  "border-color": string
  "border-image": string
  "border-image-outset": string
  "border-image-repeat": string
  "border-image-slice": string
  "border-image-source": string
  "border-image-width": string
  "border-inline-end": string
  "border-inline-end-color": string
  "border-inline-end-style": string
  "border-inline-end-width": string
  "border-inline-start": string
  "border-inline-start-color": string
  "border-inline-start-style": string
  "border-inline-start-width": string
  "border-left": string
  "border-left-color": string
  "border-left-style": string
  "border-left-width": string
  "border-radius": string
  "border-right": string
  "border-right-color": string
  "border-right-style": string
  "border-right-width": string
  "border-spacing": string
  "border-style": string
  "border-top": string
  "border-top-color": string
  "border-top-left-radius": string
  "border-top-right-radius": string
  "border-top-style": string
  "border-top-width": string
  "border-width": string
  bottom: string
  "box-shadow": string
  "box-sizing": "content-box" | "border-box"
  "break-after": string
  "break-before": string
  "break-inside": string
  "caption-side": string
  "caret-color": string
  clear: "none" | "left" | "right" | "both" | "inline-start" | "inline-end"
  clip: string
  "clip-path": string
  "clip-rule": string
  color: string
  "color-interpolation": string
  "color-interpolation-filters": string
  "color-scheme": string
  "column-count": string
  "column-fill": string
  "column-gap": string
  "column-rule": string
  "column-rule-color": string
  "column-rule-style": string
  "column-rule-width": string
  "column-span": string
  "column-width": string
  columns: string
  contain: string
  content: string
  "counter-increment": string
  "counter-reset": string
  "counter-set": string
  "css-float": string
  "css-text": string
  cursor: string
  direction: "ltr" | "rtl"
  display:
    | "none"
    | "block"
    | "inline"
    | "inline-block"
    | "flex"
    | "grid"
    | "inline-flex"
    | "inline-grid"
    | "list-item"
    | "run-in"
    | "table"
    | "table-caption"
    | "table-column-group"
    | "table-header-group"
    | "table-footer-group"
    | "table-row-group"
    | "table-cell"
    | "table-column"
    | "table-row"
    | "flow-root"
    | "contents"
  "dominant-baseline": string
  "empty-cells": "show" | "hide"
  fill: string
  "fill-opacity": string
  "fill-rule": string
  filter: string
  flex: string
  "flex-basis": string
  "flex-direction": "row" | "row-reverse" | "column" | "column-reverse"
  "flex-flow": string
  "flex-grow": string
  "flex-shrink": string
  "flex-wrap": "nowrap" | "wrap" | "wrap-reverse"
  float: "left" | "right" | "none" | "inline-start" | "inline-end"
  "flood-color": string
  "flood-opacity": string
  font: string
  "font-display": string
  "font-family": string
  "font-feature-settings": string
  "font-kerning": string
  "font-optical-sizing": string
  "font-size": string
  "font-stretch": string
  "font-style": string
  "font-synthesis": string
  "font-variant": string
  "font-variant-caps": string
  "font-variant-east-asian": string
  "font-variant-ligatures": string
  "font-variant-numeric": string
  "font-variation-settings": string
  "font-weight": string
  gap: string
  grid: string
  "grid-area": string
  "grid-auto-columns": string
  "grid-auto-flow": string
  "grid-auto-rows": string
  "grid-column": string
  "grid-column-end": string
  "grid-column-gap": string
  "grid-column-start": string
  "grid-gap": string
  "grid-row": string
  "grid-row-end": string
  "grid-row-gap": string
  "grid-row-start": string
  "grid-template": string
  "grid-template-areas": string
  "grid-template-columns": string
  "grid-template-rows": string
  height: string
  hyphens: string
  "image-orientation": string
  "image-rendering": string
  "inline-size": string
  inset: string
  "inset-block": string
  "inset-block-end": string
  "inset-block-start": string
  "inset-inline": string
  "inset-inline-end": string
  "inset-inline-start": string
  isolation: string
  "justify-content": string
  "justify-items": string
  "justify-self": string
  left: string
  "letter-spacing": string
  "lighting-color": string
  "line-break": string
  "line-height": string
  "list-style": string
  "list-style-image": string
  "list-style-position": string
  "list-style-type": string
  margin: string
  "margin-block": string
  "margin-block-end": string
  "margin-block-start": string
  "margin-bottom": string
  "margin-inline": string
  "margin-inline-end": string
  "margin-inline-start": string
  "margin-left": string
  "margin-right": string
  "margin-top": string
  marker: string
  "marker-end": string
  "marker-mid": string
  "marker-start": string
  mask: string
  "mask-composite": string
  "mask-image": string
  "mask-position": string
  "mask-repeat": string
  "mask-size": string
  "mask-type": string
  "max-block-size": string
  "max-height": string
  "max-inline-size": string
  "max-width": string
  "min-block-size": string
  "min-height": string
  "min-inline-size": string
  "min-width": string
  "mix-blend-mode": string
  "object-fit": string
  "object-position": string
  offset: string
  "offset-distance": string
  "offset-path": string
  "offset-rotate": string
  opacity: string
  order: string
  orphans: string
  outline: string
  "outline-color": string
  "outline-offset": string
  "outline-style": string
  "outline-width": string
  overflow: "visible" | "hidden" | "scroll" | "auto"
  "overflow-anchor": string
  "overflow-wrap": string
  "overflow-x": "visible" | "hidden" | "scroll" | "auto"
  "overflow-y": "visible" | "hidden" | "scroll" | "auto"
  "overscroll-behavior": string
  "overscroll-behavior-block": string
  "overscroll-behavior-inline": string
  "overscroll-behavior-x": string
  "overscroll-behavior-y": string
  padding: string
  "padding-block": string
  "padding-block-end": string
  "padding-block-start": string
  "padding-bottom": string
  "padding-inline": string
  "padding-inline-end": string
  "padding-inline-start": string
  "padding-left": string
  "padding-right": string
  "padding-top": string
  "page-break-after": string
  "page-break-before": string
  "page-break-inside": string
  "paint-order": string
  perspective: string
  "perspective-origin": string
  "place-content": string
  "place-items": string
  "place-self": string
  "pointer-events": "auto" | "none"
  position: "static" | "relative" | "absolute" | "fixed" | "sticky"
  quotes: string
  resize: string
  right: string
  rotate: string
  "row-gap": string
  "ruby-align": string
  "ruby-merge": string
  "ruby-position": string
  scale: string
  "scroll-behavior": string
  "scroll-margin": string
  "scroll-margin-block": string
  "scroll-margin-block-end": string
  "scroll-margin-block-start": string
  "scroll-margin-bottom": string
  "scroll-margin-inline": string
  "scroll-margin-inline-end": string
  "scroll-margin-inline-start": string
  "scroll-margin-left": string
  "scroll-margin-right": string
  "scroll-margin-top": string
  "scroll-padding": string
  "scroll-padding-block": string
  "scroll-padding-block-end": string
  "scroll-padding-block-start": string
  "scroll-padding-bottom": string
  "scroll-padding-inline": string
  "scroll-padding-inline-end": string
  "scroll-padding-inline-start": string
  "scroll-padding-left": string
  "scroll-padding-right": string
  "scroll-padding-top": string
  "scroll-snap-align": string
  "scroll-snap-stop": string
  "scroll-snap-type": string
  "shape-image-threshold": string
  "shape-margin": string
  "shape-outside": string
  "shape-rendering": string
  "stop-color": string
  "stop-opacity": string
  stroke: string
  "stroke-dasharray": string
  "stroke-dashoffset": string
  "stroke-linecap": string
  "stroke-linejoin": string
  "stroke-miterlimit": string
  "stroke-opacity": string
  "stroke-width": string
  "tab-size": string
  "table-layout": string
  "text-align": "left" | "right" | "center" | "justify" | "justify-all" | "start" | "end" | "match-parent"
  "text-align-last": "auto" | "left" | "right" | "center" | "justify" | "start" | "end"
  "text-anchor": string
  "text-combine-upright": string
  "text-decoration": string
  "text-decoration-color": string
  "text-decoration-line": string
  "text-decoration-skip-ink": string
  "text-decoration-style": string
  "text-decoration-thickness": string
  "text-emphasis": string
  "text-emphasis-color": string
  "text-emphasis-position": string
  "text-emphasis-style": string
  "text-indent": string
  "text-justify": string
  "text-orientation": string
  "text-overflow": string
  "text-rendering": string
  "text-shadow": string
  "text-transform": "none" | "capitalize" | "uppercase" | "lowercase" | "full-width" | "full-size-kana"
  "text-underline-offset": string
  "text-underline-position": string
  top: string
  "touch-action": string
  transform: string
  "transform-box": string
  "transform-origin": string
  "transform-style": string
  transition: string
  "transition-delay": string
  "transition-duration": string
  "transition-property": string
  "transition-timing-function": string
  "unicode-bidi": string
  "user-select": "auto" | "text" | "none" | "contain" | "all"
  "vertical-align": string
  visibility: "visible" | "hidden" | "collapse"
  "white-space": "normal" | "nowrap" | "pre" | "pre-line" | "pre-wrap"
  widows: string
  width: string
  "will-change": string
  "word-break": string
  "word-spacing": string
  "word-wrap": string
  "writing-mode": string
  "z-index": string
  zoom: string
}
